import Revenue from '../models/Revenue.js';

// Get all revenues with filters
export const getRevenues = async (req, res) => {
    try {
        const {
            page = 1,
            limit = 20,
            startDate,
            endDate,
            sourceId, // NEW: Filter by sourceId instead of source
            generatedBy, // NEW: Filter by system/manual
            category, // NEW: Filter by recurring/one-time
            search
        } = req.query;

        const query = {
            gymId: req.gymId,
            isDeleted: false
        };

        // Date range filter
        if (startDate || endDate) {
            query.revenueDate = {};
            if (startDate) query.revenueDate.$gte = new Date(startDate);
            if (endDate) query.revenueDate.$lte = new Date(endDate);
        }

        // Source filter (by sourceId)
        if (sourceId) {
            query.sourceId = sourceId;
        }

        // Generated by filter (system/manual)
        if (generatedBy) {
            query.generatedBy = generatedBy;
        }

        // Search filter
        if (search) {
            query.$or = [
                { description: { $regex: search, $options: 'i' } },
                { notes: { $regex: search, $options: 'i' } }
            ];
        }

        const skip = (page - 1) * limit;

        let revenues = await Revenue.find(query)
            .populate('sourceId') // Populate revenue source details
            .populate('paymentId')
            .populate('memberId', 'name email')
            .populate('createdBy', 'name email')
            .sort({ revenueDate: -1 })
            .limit(parseInt(limit))
            .skip(skip);

        // Filter by category if provided (requires populated sourceId)
        if (category) {
            revenues = revenues.filter(rev => rev.sourceId?.category === category);
        }

        const total = await Revenue.countDocuments(query);

        res.json({
            success: true,
            data: revenues,
            pagination: {
                page: parseInt(page),
                limit: parseInt(limit),
                total,
                pages: Math.ceil(total / limit)
            }
        });
    } catch (error) {
        console.error('Error fetching revenues:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to fetch revenues',
            error: error.message
        });
    }
};

// Get single revenue
export const getRevenue = async (req, res) => {
    try {
        const revenue = await Revenue.findOne({
            _id: req.params.id,
            gymId: req.gymId,
            isDeleted: false
        })
            .populate('paymentId')
            .populate('memberId', 'name email')
            .populate('createdBy', 'name email');

        if (!revenue) {
            return res.status(404).json({
                success: false,
                message: 'Revenue not found'
            });
        }

        res.json({
            success: true,
            data: revenue
        });
    } catch (error) {
        console.error('Error fetching revenue:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to fetch revenue',
            error: error.message
        });
    }
};

// Create revenue
export const createRevenue = async (req, res) => {
    try {
        const {
            amount,
            sourceId, // NEW: Use sourceId instead of enum source
            description,
            revenueDate,
            notes,
            paymentId,
            memberId
        } = req.body;

        // Validate sourceId is provided
        if (!sourceId) {
            return res.status(400).json({
                success: false,
                message: 'Revenue source is required'
            });
        }

        // Fetch the revenue source to validate
        const { default: RevenueSource } = await import('../models/RevenueSource.js');
        const revenueSource = await RevenueSource.findOne({
            _id: sourceId,
            gymId: req.gymId,
            isActive: true,
            isDeleted: false
        });

        if (!revenueSource) {
            return res.status(404).json({
                success: false,
                message: 'Revenue source not found or inactive'
            });
        }

        // CRITICAL: Block manual creation for auto-generated sources
        if (revenueSource.autoGenerate) {
            return res.status(400).json({
                success: false,
                message: `Cannot manually create revenue for "${revenueSource.name}". This source is auto-generated from ${revenueSource.linkedModule} payments.`,
                hint: 'Use Payment or Invoice modules instead. Revenue will be created automatically.'
            });
        }

        // Create revenue (manual)
        const revenue = await Revenue.create({
            amount,
            sourceId,
            description,
            revenueDate: revenueDate || Date.now(),
            notes,
            paymentId,
            memberId,
            gymId: req.gymId,
            createdBy: req.user._id,
            generatedBy: 'manual', // Manually created
            referenceType: paymentId ? 'payment' : null,
            referenceId: paymentId || null
        });

        const populatedRevenue = await Revenue.findById(revenue._id)
            .populate('sourceId')
            .populate('paymentId')
            .populate('memberId', 'name email')
            .populate('createdBy', 'name email');

        res.status(201).json({
            success: true,
            message: 'Revenue created successfully',
            data: populatedRevenue
        });
    } catch (error) {
        console.error('Error creating revenue:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to create revenue',
            error: error.message
        });
    }
};

// Update revenue
export const updateRevenue = async (req, res) => {
    try {
        const {
            amount,
            source,
            description,
            revenueDate,
            notes,
            paymentId,
            memberId
        } = req.body;

        const revenue = await Revenue.findOneAndUpdate(
            { _id: req.params.id, gymId: req.gymId, isDeleted: false },
            {
                amount,
                source,
                description,
                revenueDate,
                notes,
                paymentId,
                memberId
            },
            { new: true, runValidators: true }
        )
            .populate('paymentId')
            .populate('memberId', 'name email')
            .populate('createdBy', 'name email');

        if (!revenue) {
            return res.status(404).json({
                success: false,
                message: 'Revenue not found'
            });
        }

        res.json({
            success: true,
            message: 'Revenue updated successfully',
            data: revenue
        });
    } catch (error) {
        console.error('Error updating revenue:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to update revenue',
            error: error.message
        });
    }
};

// Delete revenue (soft delete)
export const deleteRevenue = async (req, res) => {
    try {
        const revenue = await Revenue.findOneAndUpdate(
            { _id: req.params.id, gymId: req.gymId, isDeleted: false },
            { isDeleted: true },
            { new: true }
        );

        if (!revenue) {
            return res.status(404).json({
                success: false,
                message: 'Revenue not found'
            });
        }

        res.json({
            success: true,
            message: 'Revenue deleted successfully'
        });
    } catch (error) {
        console.error('Error deleting revenue:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to delete revenue',
            error: error.message
        });
    }
};

// Get revenue statistics
export const getRevenueStats = async (req, res) => {
    try {
        const { startDate, endDate } = req.query;

        const query = {
            gymId: req.gymId,
            isDeleted: false,
            isReversed: false // Exclude reversed revenues
        };

        if (startDate || endDate) {
            query.revenueDate = {};
            if (startDate) query.revenueDate.$gte = new Date(startDate);
            if (endDate) query.revenueDate.$lte = new Date(endDate);
        }

        // Total revenue (collected)
        const totalRevenue = await Revenue.aggregate([
            { $match: query },
            { $group: { _id: null, total: { $sum: '$amount' }, count: { $sum: 1 } } }
        ]);

        const collected = totalRevenue.length > 0 ? totalRevenue[0].total : 0;
        const count = totalRevenue.length > 0 ? totalRevenue[0].count : 0;

        // Revenue by source (with source details)
        const revenueBySource = await Revenue.aggregate([
            { $match: query },
            {
                $group: {
                    _id: '$sourceId',
                    total: { $sum: '$amount' },
                    count: { $sum: 1 }
                }
            },
            {
                $lookup: {
                    from: 'revenuesources',
                    localField: '_id',
                    foreignField: '_id',
                    as: 'source'
                }
            },
            { $unwind: '$source' },
            {
                $project: {
                    sourceId: '$_id',
                    sourceName: '$source.name',
                    category: '$source.category',
                    icon: '$source.icon',
                    color: '$source.color',
                    total: 1,
                    count: 1
                }
            },
            { $sort: { total: -1 } }
        ]);

        // Revenue by category (recurring vs one-time)
        const revenueByCategory = await Revenue.aggregate([
            { $match: query },
            {
                $lookup: {
                    from: 'revenuesources',
                    localField: 'sourceId',
                    foreignField: '_id',
                    as: 'source'
                }
            },
            { $unwind: '$source' },
            {
                $group: {
                    _id: '$source.category',
                    total: { $sum: '$amount' },
                    count: { $sum: 1 }
                }
            },
            { $sort: { total: -1 } }
        ]);

        // Revenue by generatedBy (system vs manual)
        const revenueByType = await Revenue.aggregate([
            { $match: query },
            {
                $group: {
                    _id: '$generatedBy',
                    total: { $sum: '$amount' },
                    count: { $sum: 1 }
                }
            }
        ]);

        // Calculate expected revenue
        const { calculateCollectionEfficiency } = await import('../services/autoRevenueService.js');
        let efficiency = null;

        if (startDate && endDate) {
            try {
                efficiency = await calculateCollectionEfficiency(
                    req.gymId,
                    startDate,
                    endDate
                );
            } catch (error) {
                console.error('Error calculating efficiency:', error);
            }
        }

        res.json({
            success: true,
            data: {
                total: collected,
                count: count,
                bySource: revenueBySource,
                byCategory: revenueByCategory,
                byType: revenueByType,
                // Expected revenue metrics (if date range provided)
                ...(efficiency && {
                    expected: efficiency.expected,
                    collected: efficiency.collected,
                    pending: efficiency.pending,
                    collectionEfficiency: efficiency.efficiency
                })
            }
        });
    } catch (error) {
        console.error('Error fetching revenue stats:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to fetch revenue statistics',
            error: error.message
        });
    }
};

// NEW: Get expected revenue
export const getExpectedRevenue = async (req, res) => {
    try {
        const { startDate, endDate } = req.query;

        if (!startDate || !endDate) {
            return res.status(400).json({
                success: false,
                message: 'startDate and endDate are required'
            });
        }

        const { calculateCollectionEfficiency } = await import('../services/autoRevenueService.js');
        const result = await calculateCollectionEfficiency(
            req.gymId,
            startDate,
            endDate
        );

        res.json({
            success: true,
            data: result
        });
    } catch (error) {
        console.error('Error calculating expected revenue:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to calculate expected revenue',
            error: error.message
        });
    }
};
